### PR TITLE
163405 Image CI Pipeline does not pull the PR into the VM to build th…

### PR DESCRIPTION
**Pull request by ganeshk146**
…e image

### CODE REVIEW

**Comment by robe070** [comment]
Looks like Azure Build has succeeded in executing your changes, but I think it may be retrying the build - it automatically retries 3 times if there is a failure:
image

**Comment by robe070** [comment]
AWS CI is in same state

**Comment by ganeshk146** [comment]
> AWS CI is in same state

checking it

**Comment by ganeshk146** [comment]
> Looks like Azure Build has succeeded in executing your changes, but I think it may be retrying the build - it automatically retries 3 times if there is a failure:
> image

I don't see the failure or error

**Comment by robe070** [comment]
I was just expecting to be further through the process than it was. I had no specific message. Anyway, it has successfully built the image. But how did it execute your modified script?

**Comment by ganeshk146** [comment]
> I was just expecting to be further through the process than it was. I had no specific message. Anyway, it has successfully built the image. But how did it execute your modified script?

It seems like it because of this https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_build/results?buildId=1153&view=logs&j=8c3f0989-617d-5669-63ad-dc4309b25f44&t=12b0acf0-966b-54d8-f0b3-6be54120ceb6

**Comment by robe070** [comment]
I don't think I'm seeing what you think the link represents. So you have found something that explains why it pulled in the new script? Maybe a screen grab?

**Comment by robe070** [comment]
All looks successful to me. So I'm merging

**Comment by robe070** [comment]
The reason it was using the latest version of installGit.ps1 is because its directly executed from the local machine. Its only scripts called from within it that are picked up from the remote machine.

**Pull request merged**
