### PR TITLE
CCS 163279: Implement recommendations provided by the Azure Support #72

### PR DESCRIPTION
**Pull request by VarunChopraAccolite**
* Add the SysprepStatus registry - CleanupState (2) and GeneralizationState (7), prevents the machine is in an invalid state

### CODE REVIEW

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
I see that with the suggested changes, we are able to reproduce the same odd behavior. Please refer
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=467&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=b7ac53b1-fc2a-53cb-ebde-ce59c17928a5

**Comment by robe070** [comment]
Yes, I noticed as I get notified of pushes to PRs. 

What is your recommended next step?

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
We can raise the issue back to support, in parallel we can try adding a timeout before the VM tests. It seems to be an issue with the infra though.

**Comment by robe070** [comment]
> We can raise the issue back to support, in parallel we can try adding a timeout before the VM tests. It seems to be an issue with the infra though.

It doesn't matter how long you wait, after the image is constructed, before creating a VM from the image. In my tests some VMs would have been a week later, or more! Therefore its the construction of the image thats the issue.

It seems its either about how long since the last image was built, and/or general load on Azure. I note that over the weekend when I delayed 1 hour between builds, they all succeeded. That doesn't occur during the day. Maybe there is a case for delaying the build until, say, midnight AEST and see if that improves it.

What do I report back to Support? We implemented your recommendations and its still occurring?

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
Your call on the timeouts, we can add them before the build image option as well to have the appropriate gap. 
Yes, we can report back to the support team to get their inputs, that it's occurring after the registry changes are done.

**Comment by robe070** [comment]
Is it possible to delay a build until midnight? And I gather you are saying that each step could be delayed? 1 hour after last step finished?

**Comment by VarunChopraAccolite** [comment]
I will try from my end and keep you posted.

**Comment by robe070** [comment]
This was solved another way

**Pull request closed without merging**
